// Code generated by gen.go; DO NOT EDIT.

package EX

import (
	"context"

	"github.com/cyw0ng95/razordata/internal/SQL/LX"
	"github.com/cyw0ng95/razordata/internal/SQL/PS"
)

// FilterBatchNext returns a specialized batch-execution function.
func FilterBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processFilterBatch(ctx, batch, params)
	}
}

func processFilterBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// SeqScanBatchNext returns a specialized batch-execution function.
func SeqScanBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processSeqScanBatch(ctx, batch, params)
	}
}

func processSeqScanBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// IndexScanBatchNext returns a specialized batch-execution function.
func IndexScanBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processIndexScanBatch(ctx, batch, params)
	}
}

func processIndexScanBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// ProjectBatchNext returns a specialized batch-execution function.
func ProjectBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processProjectBatch(ctx, batch, params)
	}
}

func processProjectBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// SortBatchNext returns a specialized batch-execution function.
func SortBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processSortBatch(ctx, batch, params)
	}
}

func processSortBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// LimitBatchNext returns a specialized batch-execution function.
func LimitBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processLimitBatch(ctx, batch, params)
	}
}

func processLimitBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// NestedLoopJoinBatchNext returns a specialized batch-execution function.
func NestedLoopJoinBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processNestedLoopJoinBatch(ctx, batch, params)
	}
}

func processNestedLoopJoinBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// HashJoinBatchNext returns a specialized batch-execution function.
func HashJoinBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processHashJoinBatch(ctx, batch, params)
	}
}

func processHashJoinBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// HashAggregateBatchNext returns a specialized batch-execution function.
func HashAggregateBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processHashAggregateBatch(ctx, batch, params)
	}
}

func processHashAggregateBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// AggregateBatchNext returns a specialized batch-execution function.
func AggregateBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processAggregateBatch(ctx, batch, params)
	}
}

func processAggregateBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// DistinctBatchNext returns a specialized batch-execution function.
func DistinctBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processDistinctBatch(ctx, batch, params)
	}
}

func processDistinctBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// CompoundOpBatchNext returns a specialized batch-execution function.
func CompoundOpBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processCompoundOpBatch(ctx, batch, params)
	}
}

func processCompoundOpBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// WindowOperatorBatchNext returns a specialized batch-execution function.
func WindowOperatorBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processWindowOperatorBatch(ctx, batch, params)
	}
}

func processWindowOperatorBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// ExplainStmtOpBatchNext returns a specialized batch-execution function.
func ExplainStmtOpBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processExplainStmtOpBatch(ctx, batch, params)
	}
}

func processExplainStmtOpBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

// CreateViewOperatorBatchNext returns a specialized batch-execution function.
func CreateViewOperatorBatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return processCreateViewOperatorBatch(ctx, batch, params)
	}
}

func processCreateViewOperatorBatch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

var _ = LX.T_INT_KW
var _ = PS.NumberLiteral{}

func init() {
	registerCodegenOp("SeqScan", SeqScanBatchNext())
	registerCodegenOp("IndexScan", IndexScanBatchNext())
	registerCodegenOp("Filter", FilterBatchNext())
	registerCodegenOp("Project", ProjectBatchNext())
	registerCodegenOp("Sort", SortBatchNext())
	registerCodegenOp("Limit", LimitBatchNext())
	registerCodegenOp("NestedLoopJoin", NestedLoopJoinBatchNext())
	registerCodegenOp("HashJoin", HashJoinBatchNext())
	registerCodegenOp("HashAggregate", HashAggregateBatchNext())
	registerCodegenOp("Aggregate", AggregateBatchNext())
	registerCodegenOp("Distinct", DistinctBatchNext())
	registerCodegenOp("CompoundOp", CompoundOpBatchNext())
	registerCodegenOp("WindowOperator", WindowOperatorBatchNext())
	registerCodegenOp("ExplainStmtOp", ExplainStmtOpBatchNext())
	registerCodegenOp("CreateViewOperator", CreateViewOperatorBatchNext())
}

var _ = LX.T_INT_KW
var _ = PS.NumberLiteral{}