// Code generated by gen.go; DO NOT EDIT.

package EX

import (
	"context"
)

// REQ000576: all generated batch functions were no-ops (returning
// the input unchanged). The adaptive path would swap from the
// correct interpreted path to these no-ops, silently dropping
// all filter/project/join logic. The init() registrations have
// been removed until real implementations exist. The adaptive
// hot-path detector (AdQC) falls through to the interpreted path
// when no codegen op is registered, which is correct.

var _ = context.Background