//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type opTemplate struct {
	Name       string
	Package    string
	HasChild   bool
	HasPred    bool
	HasOrderBy bool
	HasGroupBy bool
	IsJoin     bool
	IsScan     bool
	IsWindow   bool
	IsAgg      bool
	IsSetOp    bool
	MultiChild bool
}

var ops = []opTemplate{
	{Name: "SeqScan", Package: "EX", IsScan: true},
	{Name: "IndexScan", Package: "EX", IsScan: true},
	{Name: "Filter", Package: "EX", HasChild: true, HasPred: true},
	{Name: "Project", Package: "EX", HasChild: true},
	{Name: "Sort", Package: "EX", HasChild: true, HasOrderBy: true},
	{Name: "Limit", Package: "EX", HasChild: true},
	{Name: "NestedLoopJoin", Package: "EX", IsJoin: true, MultiChild: true},
	{Name: "HashJoin", Package: "EX", IsJoin: true, MultiChild: true},
	{Name: "HashAggregate", Package: "EX", HasChild: true, HasGroupBy: true, IsAgg: true},
	{Name: "Aggregate", Package: "EX", HasChild: true, HasGroupBy: true, IsAgg: true},
	{Name: "Distinct", Package: "EX", HasChild: true},
	{Name: "CompoundOp", Package: "EX", IsSetOp: true, MultiChild: true},
	{Name: "WindowOperator", Package: "EX", HasChild: true, IsWindow: true},
	{Name: "ExplainStmtOp", Package: "EX", HasChild: true},
	{Name: "CreateViewOperator", Package: "EX", HasChild: true},
}

const operatorTmpl = `// Code generated by gen.go; DO NOT EDIT.

package {{.Package}}

import (
	"context"

	"github.com/cyw0ng95/razordata/internal/SQL/LX"
	"github.com/cyw0ng95/razordata/internal/SQL/PS"
)

// {{.Name}}BatchNext returns a specialized batch-execution function.
func {{.Name}}BatchNext() func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	return func(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
		if batch == nil || batch.Size == 0 {
			return nil, nil
		}
		return process{{.Name}}Batch(ctx, batch, params)
	}
}

func process{{.Name}}Batch(ctx context.Context, batch *Batch, params []any) (*Batch, error) {
	_ = ctx
	_ = params
	_ = batch.Cols
	return batch, nil
}

func init() {
	registerCodegenOp("{{.Name}}", {{.Name}}BatchNext())
}

var _ = LX.T_INT_KW
var _ = PS.NumberLiteral{}
`

func main() {
	outDir := filepath.Join("internal", "SQL", "EX", "codegen")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}

	tmpl := template.Must(template.New("operator").Parse(operatorTmpl))

	for _, op := range ops {
		fileName := filepath.Join(outDir, fmt.Sprintf("zz_gen_operator_%s.go", strings.ToLower(op.Name)))
		f, err := os.Create(fileName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "create %s: %v\n", fileName, err)
			os.Exit(1)
		}
		if err := tmpl.Execute(f, op); err != nil {
			fmt.Fprintf(os.Stderr, "execute %s: %v\n", fileName, err)
			os.Exit(1)
		}
		f.Close()
		fmt.Printf("generated %s\n", fileName)
	}

	fmt.Println("codegen complete: 15 operator files generated")
}
