package sqlcmp

import "testing"

var selectCases = []testCase{
	{"simple_select", "SELECT * FROM t", false},
	{"select_columns", "SELECT a, b, c FROM t", false},
	{"select_where", "SELECT * FROM t WHERE a = 1", false},
	{"select_where_ne", "SELECT * FROM t WHERE a != 1", false},
	{"select_where_lt", "SELECT * FROM t WHERE a < 1", false},
	{"select_where_le", "SELECT * FROM t WHERE a <= 1", false},
	{"select_where_gt", "SELECT * FROM t WHERE a > 1", false},
	{"select_where_ge", "SELECT * FROM t WHERE a >= 1", false},
	{"select_order_by", "SELECT * FROM t ORDER BY a", false},
	{"select_order_by_desc", "SELECT * FROM t ORDER BY a DESC", false},
	{"select_limit", "SELECT * FROM t LIMIT 10", false},
	{"select_offset", "SELECT * FROM t OFFSET 5", false},
	{"select_limit_offset", "SELECT * FROM t LIMIT 10 OFFSET 5", false},
	{"select_where_and", "SELECT * FROM t WHERE a = 1 AND b = 2", false},
	{"select_where_or", "SELECT * FROM t WHERE a = 1 OR b = 2", false},
	{"select_where_and_or", "SELECT * FROM t WHERE a = 1 AND b = 2 OR c = 3", false},
	{"select_where_not", "SELECT * FROM t WHERE NOT a = 1", false},
	{"select_where_in", "SELECT * FROM t WHERE a IN (1, 2, 3)", false},
	{"select_where_between", "SELECT * FROM t WHERE a BETWEEN 1 AND 10", false},
	{"select_where_like", "SELECT * FROM t WHERE a LIKE '%foo%'", false},
	{"select_where_is_null", "SELECT * FROM t WHERE a IS NULL", false},
	{"select_where_is_not_null", "SELECT * FROM t WHERE a IS NOT NULL", false},
	{"select_expr_plus", "SELECT a + b FROM t", false},
	{"select_expr_minus", "SELECT a - b FROM t", false},
	{"select_expr_star", "SELECT a * b FROM t", false},
	{"select_expr_slash", "SELECT a / b FROM t", false},
	{"select_expr_precedence", "SELECT a + b * c FROM t", false},
	{"select_expr_precedence2", "SELECT a * b + c FROM t", false},
	{"select_expr_parens", "SELECT (a + b) * c FROM t", false},
	{"select_expr_unary_minus", "SELECT -a FROM t", false},
	{"select_expr_unary_plus", "SELECT +a FROM t", false},
	{"select_int", "SELECT 42 FROM t", false},
	{"select_float", "SELECT 3.14 FROM t", false},
	{"select_string", "SELECT 'hello world' FROM t", false},
	{"select_param", "SELECT ? FROM t", false},
	{"select_star_where", "SELECT * FROM t WHERE a = 1", false},
	{"select_all_cols", "SELECT * FROM t WHERE a = 1 AND b = 2 ORDER BY c LIMIT 10 OFFSET 5", false},
	{"select_nested_parens", "SELECT * FROM t WHERE (((a = 1)))", false},
	{"select_multi_where_and", "SELECT * FROM t WHERE a = 1 AND b = 2 AND c = 3", false},
	{"select_multi_where_or", "SELECT * FROM t WHERE a = 1 OR b = 2 OR c = 3", false},
	{"select_complex_expr", "SELECT a + b * c - d / e FROM t", false},
	{"select_negated_expr", "SELECT * FROM t WHERE NOT (a = 1 AND b = 2)", false},
	{"select_order_by_multiple", "SELECT * FROM t ORDER BY a, b, c", false},
	{"select_order_by_asc_desc", "SELECT * FROM t ORDER BY a ASC, b DESC", false},
	{"select_limit_offset_both", "SELECT * FROM t WHERE a > 0 ORDER BY b LIMIT 100 OFFSET 10", false},
	{"select_float_negative", "SELECT -2.5 FROM t", false},
	{"select_not_expr", "SELECT NOT a FROM t", false},
	{"select_null", "SELECT NULL FROM t", false},
	{"select_bool_true", "SELECT TRUE FROM t", false},
	{"select_bool_false", "SELECT FALSE FROM t", false},
	{"select_complex_where", "SELECT * FROM t WHERE (a + b) * c > 10", false},
	{"select_where_eq_string", "SELECT * FROM t WHERE a = 'foo'", false},
	{"select_where_ne_string", "SELECT * FROM t WHERE a != 'bar'", false},
	{"select_where_like_underscore", "SELECT * FROM t WHERE a LIKE 'foo_'", false},
	{"select_where_like_percent", "SELECT * FROM t WHERE a LIKE '%foo%' AND b > 0", false},
	{"select_where_is", "SELECT * FROM t WHERE a IS 1", false},
	{"select_multiple_and", "SELECT * FROM t WHERE a = 1 AND b = 2 AND c = 3 AND d = 4", false},
	{"select_large_int", "SELECT 1234567890 FROM t", false},
	{"select_negative_int", "SELECT -999999999 FROM t", false},
	{"select_float_large", "SELECT 314159265358979.0 FROM t", false},
	{"select_escape_quote", "SELECT 'it''s a test' FROM t", false},
	{"select_escape_newline", "SELECT 'line1\nline2' FROM t", false},
	{"select_escape_tab", "SELECT 'col1\tcol2' FROM t", false},
	{"select_empty_string", "SELECT '' FROM t", false},
	{"select_string_with_quotes", "SELECT 'a''b''c' FROM t", false},
	{"select_string_backslash", "SELECT 'path\\to\\file' FROM t", false},
	{"select_null_comp", "SELECT * FROM t WHERE a IS NULL OR a IS NOT NULL", false},
	{"select_null_and", "SELECT * FROM t WHERE a = 1 AND b IS NULL", false},
	{"select_null_or", "SELECT * FROM t WHERE a = 1 OR b IS NULL", false},
	{"select_expr_all_ops", "SELECT a + b - c * d / e FROM t", false},
	{"select_expr_parens_nested", "SELECT ((a + b) * (c - d)) FROM t", false},
	{"select_expr_unary_nested", "SELECT -(-a) FROM t", false},
	{"select_where_complex", "SELECT * FROM t WHERE (a + b) * c > d AND e < f OR g = h", false},
	{"select_order_by_expr", "SELECT * FROM t ORDER BY a + b", false},
	{"select_order_by_desc_expr", "SELECT * FROM t ORDER BY a * b DESC", false},
	{"select_limit_expr", "SELECT * FROM t LIMIT a + 1", false},
	{"select_offset_expr", "SELECT * FROM t OFFSET a - b", false},
	{"select_limit_offset_expr", "SELECT * FROM t LIMIT a + 1 OFFSET b - 2", false},
	{"select_case_simple", "SELECT CASE a WHEN 1 THEN 'one' WHEN 2 THEN 'two' ELSE 'other' END FROM t", false},
	{"select_case_no_expr", "SELECT CASE WHEN a > 0 THEN 'positive' ELSE 'non-positive' END FROM t", false},
	{"select_case_nested", "SELECT CASE a WHEN 1 THEN CASE b WHEN 1 THEN 'one-one' ELSE 'one-other' END ELSE 'other' END FROM t", false},
	{"select_count_star", "SELECT COUNT(*) FROM t", false},
	{"select_count_col", "SELECT COUNT(a) FROM t", false},
	{"select_sum_col", "SELECT SUM(a) FROM t", false},
	{"select_avg_col", "SELECT AVG(a) FROM t", false},
	{"select_min_col", "SELECT MIN(a) FROM t", false},
	{"select_max_col", "SELECT MAX(a) FROM t", false},
	{"select_agg_multiple", "SELECT COUNT(*), SUM(a), AVG(b) FROM t", false},
	{"select_alias_col", "SELECT a AS b FROM t", false},
	{"select_alias_multiple", "SELECT a AS x, b AS y FROM t", false},
	{"select_alias_col", "SELECT a AS b FROM t", false},
	{"select_alias_multiple", "SELECT a AS x, b AS y FROM t", false},
	{"select_alias_table", "SELECT * FROM t AS x", false},
	{"select_distinct", "SELECT DISTINCT a FROM t", false},
	{"select_distinct_multi", "SELECT DISTINCT a, b FROM t", false},
	{"select_qualified_col", "SELECT t.a FROM t", false},
	{"select_inner_join", "SELECT a.id, b.y FROM a INNER JOIN b ON b.a_id = a.id", false},
	{"select_cross_join", "SELECT * FROM a CROSS JOIN b", false},
	{"select_group_by", "SELECT a, SUM(b) FROM t GROUP BY a", false},
	{"select_having", "SELECT a, SUM(b) FROM t GROUP BY a HAVING SUM(b) > 5", false},
	{"select_exists", "SELECT * FROM t WHERE EXISTS (SELECT 1 FROM t)", false},
	{"select_in_subquery", "SELECT * FROM t WHERE a IN (SELECT a FROM t)", false},
	{"select_scalar_subquery", "SELECT (SELECT 1) FROM t", false},
	{"select_cast", "SELECT CAST(a AS INTEGER) FROM t", false},
}

func TestSelectRewrite(t *testing.T) {
	for _, tc := range selectCases {
		t.Run(tc.name, tc.runRewrite)
	}
}

func TestSelectParse(t *testing.T) {
	for _, tc := range selectCases {
		t.Run(tc.name, tc.runParse)
	}
}
